apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nexus3
  name: nexus3
metadata:
  name: {{ include "nexus-gcs.fullname" . }}
  labels:
{{ include "nexus-gcs.labels" . | indent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1235
      name: "1235"
  selector:
    app.kubernetes.io/name: {{ include "nexus-gcs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}  
