apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexus-gcs.fullname" . }}
  labels:
{{ include "nexus-gcs.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nexus-gcs.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nexus-gcs.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /run/secrets/google_application_credentials
        name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8081
        resources: {}
        volumeMounts:
        - mountPath: /run/secrets/google_application_credentials
          name: google_application_credentials
        - mountPath: /nexus-data
          name: nexus3-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: google_application_credentials
        secret:
          items:
          - key: google_application_credentials
            path: google_application_credentials
          secretName: google_application_credentials
      - name: nexus3-data
        persistentVolumeClaim:
          claimName: nexus3-data
status: {}
